### ISSUE TITLE
求加个好友，交流一下细节

### ISSUE THREAD

**Issue by lxb6476** [liudaac/kafka-ui-0.7.2#1]
你好，对于kafka-ui的原仓库实现，在基于kraft部署时，我也遇到了同样的问题，那个active controller展示的是broker节点id，但是按照理解active controller应该出现在controller节点中。在本仓库中看到你的实现是通过jmx获取的真正的active controller id，想交流一下细节，方便加个qq交流一下吗？我的qq：1003582622

**Comment by liudaac** [comment]
你好，感谢关注。qq不咋用了，可以加wx讨论 liudaac

**Comment by liudaac** [comment]
已加
